### ISSUE TITLE
[Question] Cannot capture events from TraceLogging Provider: Microsoft.Windows.Kernel.Power and Microsoft.Windows.Power.SleepStudy

### ISSUE THREAD

**Issue by guliteb** [repnz/etw-providers-docs#2]
Hi Ori Damari,
I found this repo when I was looking for ETW providers for my program. It is really useful and helpful to me.

But I get problems when dealing with some TraceLogging providers, such as Microsoft.Windows.Kernel.Power and Microsoft.Windows.Power.SleepStudy.

I want to capture events real time from some TraceLogging Providers: Microsoft.Windows.Kernel.Power and Microsoft.Windows.Power.SleepStudy. But I cannot see any events from them with TDH/Trace APIs. However, events are captured in ETL by WPR and shown in WPA.

Any comment is appreciated.

Kevin

**Comment by repnz** [comment]
Note that these providers are not trace-logging providers but manifest based providers. Tlg is basically a wrapper around ETW that allows easier and simpler logging. You can look here for a list of trace-logging providers: https://github.com/repnz/tracelogging-providers

Anyway, I tried to register to Microsoft.Windows.Kernel.Power and for me it works, I guess there's an issue in your code... I'm doing it using the Python PyWinTrace API, you can see here:

1 - install Python3
2 - pip install pywintrace
3 - run this script as admin:

```python
import etw
import etw.evntrace
import time
import pprint


def print_event(e):
    pprint.pprint(e)


def main():
    provider = etw.ProviderInfo(
                None,
                etw.GUID("{331c3b3a-2005-44c2-ac5e-77220c37d6b4}"),
                level=etw.evntrace.TRACE_LEVEL_VERBOSE,
                any_keywords=0xffffffffffffffff
            )

    session = etw.ETW(providers=[provider], event_callback=print_event)
    session.start()

    try:
        input()
    except KeyboardInterrupt:
        pass

    session.stop()


if __name__ == '__main__':
    main()
```


It should start printing events.

**Comment by guliteb** [comment]
Thanks for replying with the details. Yes, I can also get events now with TDH APIs.
